version: '3'
services:
  client:
    build:
      context: ./client
      args:
        NODE_ENV: production
    command: yarn dev
    volumes:
      - ./client:/app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
  server:
    build:
      context: ./server
      args:
        NODE_ENV: production
    command: yarn start
    volumes:
      - ./server:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

